export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';

export const GET_PROJECT = 'GET_PROJECT';
export const PROJECT_ERROR = 'PROJECT_ERROR';

export const EDIT_PROJECT = 'EDIT_PROJECT';
export const ERROR_EDIT_PROJECT = 'ERROR_EDIT_PROJECT';

export const DELETE_PROJECT = 'DELETE_PROJECT';
export const ERROR_DELETE_PROJECT = 'ERROR_DELETE_PROJECT';

export const REACTIVATE_PROJECT = 'REACTIVATE_PROJECT';
export const ERROR_REACTIVATE_PROJECT = 'ERROR_REACTIVATE_PROJECT';

export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR';

export const USERS_REGISTER = 'USERS_REGISTER';
export const USERS_REGISTER_ERROR = 'USERS_REGISTER_ERROR';

export const USERS_DELETE = 'USERS_DELETE';
export const USERS_DELETE_ERROR = 'USERS_DELETE_ERROR';

export const INSERT_RISK = 'INSERT_RISK';
export const ERROR_RISK = 'ERROR_RISK';

export const GET_RISKS = 'GET_RISKS';
export const ERROR_GET_RISK = 'ERROR_GET_RISK';

export const DELETE_RISKS = 'DELETE_RISKS';
export const ERROR_DELETE_RISK = 'ERROR_DELETE_RISK';

export const GET_PROJECT_TYPE = 'GET_PROJECT_TYPE';
export const ERROR_PROJECT_TYPE = 'ERROR_PROJECT_TYPE';

export const INSERT_PROJECT_TYPE = 'INSERT_PROJECT_TYPE';
export const ERROR_INSERT_PROJECT_TYPE = 'ERROR_INSERT_PROJECT_TYPE';

export const EDIT_PROJECT_TYPE = 'EDIT_PROJECT_TYPE';
export const ERROR_EDIT_PROJECT_TYPE = 'ERROR_EDIT_PROJECT_TYPE';

export const DELETE_PROJECT_TYPE = 'DELETE_PROJECT_TYPE';
export const ERROR_DELETE_PROJECT_TYPE = 'ERROR_DELETE_PROJECT_TYPE';

export const GET_PROJECT_SUBTYPE = 'GET_PROJECT_SUBTYPE';
export const ERROR_PROJECT_SUBTYPE = 'ERROR_PROJECT_SUBTYPE';

export const INSERT_PROJECT_SUBTYPE = 'INSERT_PROJECT_SUBTYPE';
export const ERROR_INSERT_PROJECT_SUBTYPE = 'ERROR_INSERT_PROJECT_SUBTYPE';

export const EDIT_PROJECT_SUBTYPE = 'EDIT_PROJECT_SUBTYPE';
export const ERROR_EDIT_PROJECT_SUBTYPE = 'ERROR_EDIT_PROJECT_SUBTYPE';

export const DELETE_PROJECT_SUBTYPE = 'DELETE_PROJECT_SUBTYPE';
export const ERROR_DELETE_PROJECT_SUBTYPE = 'ERROR_DELETE_PROJECT_SUBTYPE';


export const GET_TASK = 'GET_TASK';
export const ERROR_TASK = 'ERROR_TASK';

export const INSERT_TASK = 'INSERT_TASK';
export const ERROR_INSERT_TASK = 'ERROR_INSERT_TASK';

export const DELETE_TASK = 'DELETE_TASK';
export const ERROR_DELETE_TASK = 'ERROR_DELETE_TASK';

export const EDIT_TASK = 'EDIT_TASK';
export const ERROR_EDIT_TASK = 'ERROR_EDIT_TASK';

export const GET_DETAIL_USER = 'GET_DETAIL_USER';
export const ERROR_GET_DETAIL_USER = 'ERROR_GET_DETAIL_USER';

export const EDIT_USER = 'EDIT_USER';
export const ERROR_EDIT_USER = 'ERROR_EDIT_USER';

export const EDIT_GRAL = 'EDIT_GRAL';
export const ERROR_EDIT_GRAL = 'ERROR_EDIT_GRAL';

export const GET_CLIENT = 'GET_CLIENT';
export const ERROR_GET_CLIENT = 'ERROR_GET_CLIENT';

export const INSERT_CLIENT = 'INSERT_CLIENT';
export const ERROR_INSERT_CLIENT = 'ERROR_INSERT_CLIENT';

export const DELETE_CLIENT = 'DELETE_CLIENT';
export const ERROR_DELETE_CLIENT = 'ERROR_DELETE_CLIENT';

export const EDIT_CLIENT = 'EDIT_CLIENT';
export const ERROR_EDIT_CLIENT = 'ERROR_EDIT_CLIENT';

export const GET_AGENT = 'GET_AGENT';
export const ERROR_GET_AGENT = 'ERROR_GET_AGENT';

export const INSERT_AGENT = 'INSERT_AGENT';
export const ERROR_INSERT_AGENT = 'ERROR_INSERT_AGENT';

export const DELETE_AGENT = 'DELETE_AGENT';
export const ERROR_DELETE_AGENT = 'ERROR_DELETE_AGENT';

export const EDIT_AGENT = 'EDIT_CLIENT';
export const ERROR_EDIT_AGENT = 'ERROR_EDIT_AGENT';

export const GET_AGENT_ACTIVE = 'GET_AGENT_ACTIVE';
export const ERROR_GET_AGENT_ACTIVE = 'ERROR_GET_AGENT_ACTIVE';

export const GET_CLIENT_AGENTS = 'GET_CLIENT_AGENTS';
export const ERROR_GET_CLIENT_AGENTS = 'ERROR_GET_CLIENT_AGENTS';

export const INSERT_AGENT_CLIENT = 'INSERT_AGENT_CLIENT';
export const ERROR_INSERT_AGENT_CLIENT = 'ERROR_INSERT_AGENT_CLIENT';

export const GET_PROVINCE = 'GET_PROVINCE';
export const ERROR_GET_PROVINCE = 'ERROR_GET_PROVINCE';

export const GET_LOCATION = 'GET_LOCATION';
export const ERROR_GET_LOCATION = 'ERROR_GET_LOCATION';

export const INSERT_LOCATION = 'INSERT_LOCATION';
export const ERROR_INSERT_LOCATION = 'ERROR_INSERT_LOCATION';

export const DELETE_LOCATION = 'DELETE_LOCATION';
export const ERROR_DELETE_LOCATION = 'ERROR_DELETE_LOCATION';

export const INSERT_PROVINCE = 'INSERT_PROVINCE';
export const ERROR_INSERT_PROVINCE = 'ERROR_INSERT_PROVINCE';

export const DELETE_PROVINCE = 'DELETE_PROVINCE';
export const ERROR_DELETE_PROVINCE = 'ERROR_DELETE_PROVINCE';

export const EDIT_LOCATION = 'EDIT_LOCATION';
export const ERROR_EDIT_LOCATION = 'ERROR_EDIT_LOCATION';

export const EDIT_PROVINCE = 'EDIT_PROVINCE';
export const ERROR_EDIT_PROVINCE = 'ERROR_EDIT_PROVINCE';

export const GET_TEAM = 'GET_TEAM';
export const ERROR_GET_TEAM = 'ERROR_GET_TEAM';

export const INSERT_TEAM = 'INSERT_TEAM';
export const ERROR_INSERT_TEAM = 'ERROR_INSERT_TEAM';

export const GET_TEAM_USERS = 'GET_TEAM_USERS';
export const ERROR_GET_TEAM_USERS = 'ERROR_GET_TEAM_USERS';

export const USER_TEAM_DELETE = 'USER_TEAM_DELETE';
export const ERROR_USER_TEAM_DELETE = 'ERROR_USER_TEAM_DELETE';

export const EDIT_TEAM = 'EDIT_TEAM';
export const ERROR_EDIT_TEAM = 'ERROR_EDIT_TEAM';

export const GET_USER_ACTIVE = 'GET_USER_ACTIVE';
export const ERROR_GET_USER_ACTIVE = 'ERROR_GET_USER_ACTIVE';

export const GET_STAGE = 'GET_STAGE';
export const ERROR_STAGE = 'ERROR_STAGE';

export const INSERT_STAGE = 'INSERT_STAGE';
export const ERROR_INSERT_STAGE = 'ERROR_INSERT_STAGE';

export const EDIT_STAGE = 'EDIT_STAGE';
export const ERROR_EDIT_STAGE = 'ERROR_EDIT_STAGE';

export const DELETE_STAGE = 'DELETE_STAGE';
export const ERROR_DELETE_STAGE = 'ERROR_DELETE_STAGE';

export const REACTIVATE_STAGE = 'REACTIVATE_STAGE';
export const ERROR_REACTIVATE_STAGE = 'ERROR_REACTIVATE_STAGE';

export const GET_ACTIVITY = 'GET_ACTIVITY';
export const ERROR_ACTIVITY = 'ERROR_ACTIVITY';

export const DELETE_ACTIVITY = 'DELETE_ACTIVITY';
export const ERROR_DELETE_ACTIVITY = 'ERROR_DELETE_ACTIVITY';

export const REACTIVATE_ACTIVITY = 'REACTIVATE_ACTIVITY';
export const ERROR_REACTIVATE_ACTIVITY = 'ERROR_REACTIVATE_ACTIVITY';

export const DELETE_TASK_ACTIVITY  = 'DELETE_TASK_ACTIVITY ';
export const ERROR_DELETE_TASK_ACTIVITY = 'ERROR_DELETE_TASK_ACTIVITY';

export const REACTIVATE_TASK  = 'REACTIVATE_TASK ';
export const ERROR_REACTIVATE_TASK = 'ERROR_REACTIVATE_TASK';

export const TERMINATE_TASK  = 'TERMINATE_TASK ';
export const ERROR_TERMINATE_TASK = 'ERROR_TERMINATE_TASK';

export const INSERT_DEDICATION = 'INSERT_DEDICATION';
export const ERROR_INSERT_DEDICATION = 'ERROR_INSERT_DEDICATION';


export const DETAIL_PROJECT = 'DETAIL_PROJECT';
export const ERROR_DETAIL_PROJECT = 'ERROR_DETAIL_PROJECT';

export const GET_RELATION = 'GET_RELATION';
export const ERROR_GET_RELATION = 'ERROR_GET_RELATION';


export const GET_TASK_RELATION = 'GET_TASK_RELATION';
export const ERROR_GET_TASK_RELATION= 'ERROR_GET_TASK_RELATION';

export const GET_USER_TASK = 'GET_USER_TASK';
export const ERROR_GET_USER_TASK = 'ERROR_GET_USER_TASK';

