export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const GET_PROFILE = 'GET_PROFILE';
export const PROFILE_ERROR = 'PROFILE_ERROR';
export const GET_PROJECT = 'GET_PROJECT';
export const PROJECT_ERROR = 'PROJECT_ERROR';
export const GET_USERS = 'GET_USERS';
export const USERS_ERROR = 'USERS_ERROR';

export const USERS_REGISTER = 'USERS_REGISTER';
export const USERS_REGISTER_ERROR = 'USERS_REGISTER_ERROR';

export const USERS_DELETE = 'USERS_DELETE';
export const USERS_DELETE_ERROR = 'USERS_DELETE_ERROR';

export const INSERT_RISK = 'INSERT_RISK';
export const ERROR_RISK = 'ERROR_RISK';

export const GET_RISKS = 'GET_RISKS';
export const ERROR_GET_RISK = 'ERROR_GET_RISK';

export const DELETE_RISKS = 'DELETE_RISKS';
export const ERROR_DELETE_RISK = 'ERROR_DELETE_RISK';

export const GET_PROJECT_TYPE = 'GET_PROJECT_TYPE';
export const ERROR_PROJECT_TYPE = 'ERROR_PROJECT_TYPE';

export const INSERT_PROJECT_TYPE = 'INSERT_PROJECT_TYPE';
export const ERROR_INSERT_PROJECT_TYPE = 'ERROR_INSERT_PROJECT_TYPE';

export const DELETE_PROJECT_TYPE = 'DELETE_PROJECT_TYPE';
export const ERROR_DELETE_PROJECT_TYPE = 'ERROR_DELETE_PROJECT_TYPE';

export const GET_PROJECT_SUBTYPE = 'GET_PROJECT_SUBTYPE';
export const ERROR_PROJECT_SUBTYPE = 'ERROR_PROJECT_SUBTYPE';

export const INSERT_PROJECT_SUBTYPE = 'INSERT_PROJECT_SUBTYPE';
export const ERROR_INSERT_PROJECT_SUBTYPE = 'ERROR_INSERT_PROJECT_SUBTYPE';


export const DELETE_PROJECT_SUBTYPE = 'DELETE_PROJECT_SUBTYPE';
export const ERROR_DELETE_PROJECT_SUBTYPE = 'ERROR_DELETE_PROJECT_SUBTYPE';


export const GET_TASK = 'GET_TASK';
export const ERROR_TASK = 'ERROR_TASK';




